### ISSUE TITLE
Download fails

### ISSUE THREAD

**Issue by Chipsum** [Scotty-Retro/Neon-BlastV1#9]
Hi, I wish I can use the theme but all downloads are failing whether directly from GitHub or Batocera.
Is there any chance to get download links for google drive or mega..etc
Thank you so much :smiley:

**Comment by Scotty-Retro** [comment]
@Chipsum sure I'll upload it somewhere else next time I add an update. No idea why it fails maybe something to do with the size it is big. I don't know any themes this size

**Comment by Chipsum** [comment]
Finally it's working, What a nice glowing theme !
Thank you so much Sir Scotty :smiley: 
![screenshot-2023 03 24-17h09 29](https://user-images.githubusercontent.com/37517008/227581404-6029e5a4-9baa-4538-9566-0d891f4619fa.png)

**Comment by D4rkPh0en1x** [comment]
Hi
I have the same issue too :/
Download during 15 minutes and than stops and nothing. It also only downloads with 60MBit but could be much faster normally… all other themes works…
I’m now trying to download your file from mega but need than to figure out how to use - never installed a theme manually but I think it shouldn’t be complicate…
Hope mega works as I don’t own a membership with them as I have my own cloud on my own server…

**Comment by Scotty-Retro** [comment]
> Hi I have the same issue too :/ Download during 15 minutes and than stops and nothing. It also only downloads with 60MBit but could be much faster normally… all other themes works… I’m now trying to download your file from mega but need than to figure out how to use - never installed a theme manually but I think it shouldn’t be complicate… Hope mega works as I don’t own a membership with them as I have my own cloud on my own server…

Hello @D4rkPh0en1x alot of people are having downloads I've also just updated the theme through github so would recommend trying again maybe using a different browser. I use google chrome and personally never have a problem with the downloading of the theme. If you only manage to get it from the mega link you can extract it to the themes folder manually for example if you're using retrobat it would go in RetroBat/emulationstation/.emulationstation/themes 
Hope this helps!
